import typescriptEslintParser from '@typescript-eslint/parser';
import typescriptEslintPlugin from '@typescript-eslint/eslint-plugin';
import stylistic from '@stylistic/eslint-plugin';
import jsGlobals from 'globals';

const globals = {
  // Browser globals:
  ...jsGlobals.browser,
  ...jsGlobals.serviceworker,
  ...jsGlobals.worker,
};

export default [
  {
    files: ['**/*.ts'],
    languageOptions: {
      parser: typescriptEslintParser,
      parserOptions: {
        ecmaVersion: 'latest',
        sourceType: 'module',
        project: './tsconfig.json',
      },
      globals,
    },
    plugins: {
      '@typescript-eslint': typescriptEslintPlugin,
      '@stylistic': stylistic,
    },
    rules: {
      '@typescript-eslint/consistent-type-imports': 'warn',
      '@typescript-eslint/no-non-null-assertion': 'warn',
      '@typescript-eslint/no-explicit-any': 'warn',
      '@typescript-eslint/no-shadow': 2,
      '@typescript-eslint/no-unused-vars': [
        'error',
        {
          args: 'all',
          argsIgnorePattern: '^_',
          caughtErrors: 'all',
          caughtErrorsIgnorePattern: '^_',
          destructuredArrayIgnorePattern: '^_',
          varsIgnorePattern: '^_',
        },
      ],
      '@typescript-eslint/member-delimiter-style': [
        'error',
        {
          multiline: { delimiter: 'semi', requireLast: true },
          singleline: { delimiter: 'semi', requireLast: false },
          multilineDetection: 'brackets',
        },
      ],
      '@typescript-eslint/type-annotation-spacing': 'error',
      '@typescript-eslint/no-use-before-define': [2, 'nofunc'],
      strict: [2, 'never'],
      'no-shadow-restricted-names': 2,
      'no-cond-assign': [2, 'always'],
      'no-console': 1,
      'no-debugger': 1,
      'no-alert': 1,
      'no-constant-condition': 1,
      'no-dupe-keys': 2,
      'no-duplicate-case': 2,
      'no-empty': 2,
      'no-ex-assign': 2,
      'no-extra-boolean-cast': 0,
      'no-func-assign': 2,
      'no-inner-declarations': 2,
      'no-invalid-regexp': 2,
      'no-irregular-whitespace': 2,
      'no-obj-calls': 2,
      'no-sparse-arrays': 2,
      'no-unreachable': 2,
      'use-isnan': 2,
      'block-scoped-var': 0,
      'consistent-return': 2,
      curly: [2, 'multi-line'],
      'default-case': 2,
      'dot-notation': [2, { allowKeywords: true }],
      eqeqeq: 2,
      'guard-for-in': 2,
      'no-caller': 2,
      'no-else-return': 2,
      'no-eq-null': 2,
      'no-eval': 2,
      'no-extend-native': 2,
      'no-extra-bind': 2,
      'no-fallthrough': 2,
      'no-implied-eval': 2,
      'no-lone-blocks': 2,
      'no-loop-func': 2,
      'no-multi-str': 2,
      'no-global-assign': 2,
      'no-new': 2,
      'no-new-func': 2,
      'no-new-wrappers': 2,
      'no-octal': 2,
      'no-octal-escape': 2,
      'no-param-reassign': 2,
      'no-proto': 2,
      'no-redeclare': 2,
      'no-return-assign': 2,
      'no-script-url': 2,
      'no-self-compare': 2,
      'no-sequences': 2,
      'no-throw-literal': 2,
      'no-with': 2,
      'no-object-constructor': 2,
      yoda: 2,
      '@stylistic/no-extra-semi': 2,
      '@stylistic/no-floating-decimal': 2,
      '@stylistic/wrap-iife': [2, 'any'],
      '@stylistic/indent': [2, 2],
      '@stylistic/brace-style': [2, '1tbs', { allowSingleLine: true }],
      '@stylistic/quotes': [2, 'single', 'avoid-escape'],
      '@stylistic/comma-spacing': [2, { before: false, after: true }],
      '@stylistic/comma-style': [2, 'last'],
      '@stylistic/eol-last': 2,
      '@stylistic/key-spacing': [2, { beforeColon: false, afterColon: true }],
      '@stylistic/no-multiple-empty-lines': [2, { max: 2 }],
      '@stylistic/no-trailing-spaces': 2,
      '@stylistic/padded-blocks': [2, 'never'],
      '@stylistic/semi': ['error', 'always'],
      '@stylistic/semi-spacing': [2, { before: false, after: true }],
      '@stylistic/space-infix-ops': 2,
      camelcase: [2, { properties: 'never' }],
      'no-nested-ternary': 2,
      'no-underscore-dangle': 0,
      'one-var': [2, 'never'],
      '@stylistic/arrow-parens': ['error', 'always'],
      '@stylistic/arrow-spacing': 'error',
      '@stylistic/block-spacing': ['error', 'always'],
      '@stylistic/keyword-spacing': [
        'error',
        { before: true, after: true },
      ],
      '@stylistic/space-before-blocks': ['error', 'always'],
      '@stylistic/space-before-function-paren': [
        'error',
        {
          anonymous: 'never',
          named: 'never',
          asyncArrow: 'always',
        },
      ],
      '@stylistic/space-in-parens': ['error', 'never'],
      '@stylistic/space-unary-ops': [
        'error',
        { words: true, nonwords: false },
      ],
      '@stylistic/object-curly-spacing': ['error', 'always'],
      '@stylistic/object-curly-newline': [
        'error',
        {
          multiline: true,
          consistent: true,
        },
      ],
      '@stylistic/object-property-newline': [
        'error',
        { allowAllPropertiesOnSameLine: false },
      ],
      '@stylistic/array-bracket-spacing': ['error', 'never'],
      '@stylistic/array-bracket-newline': [
        'error',
        { multiline: true, minItems: 3 },
      ],
      '@stylistic/newline-per-chained-call': [
        'error',
        { ignoreChainWithDepth: 2 },
      ],
      '@stylistic/operator-linebreak': [
        'error',
        'before',
        { overrides: { '=': 'after' } },
      ],
      '@stylistic/template-curly-spacing': ['error', 'never'],
      '@stylistic/func-call-spacing': ['error', 'never'],
    },
  },
];
